/* 
 * Tpay.com Technical Documentation
 *
 *  <p class=\"changes-disclaimer\"> Demo transaction/masspayments api key: <input type=\"text\" id=\"transaction_key\" value=\"75f86137a6635df826e3efe2e66f7c9a946fdde1\" class=\"ui-form-control\"/><label for=\"transaction_key\" style=\"display: none;\" id=\"tr_api_label\">COPIED!</label><br/><br/> Demo cards api key: <input type=\"text\" id=\"cards_key\" value=\"ba9a05faa697f9b43f39b84933ff168e373c6496\" class=\"ui-form-control\"/><label for=\"cards_key\" style=\"display: none;\" id=\"cards_api_label\">COPIED!</label><br/><br/> Demo registration api key: <input type=\"text\" id=\"registration_key\" value=\"6c0f5ef6e4d6877abad7fcfb3b5de117ad8b772d\" class=\"ui-form-control\"/><label for=\"registration_key\" style=\"display: none;\" id=\"registration_api_label\">COPIED!</label><br/><br/> The terms seller and merchant are used interchangeably and they both refer to a person or a company registered at tpay.com to accept online payments. <br/> Whenever term merchant panel is used it refers to the part of tpay.com website located at <a href=\"https://secure.tpay.com/panel\" target=\"_blank\">secure.tpay.com/panel</a>. <br/><br/> For sandbox purposes use merchant demo account <br/><br/> ID - 1010, Password - demo<br/><br/>Remember that this is a shared account, so all data passed through will be publicly visible.</p>
 *
 * OpenAPI spec version: 1.1.1
 * Contact: pt@tpay.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// MasspaymentPacksFields
    /// </summary>
    [DataContract]
    public partial class MasspaymentPacksFields :  IEquatable<MasspaymentPacksFields>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MasspaymentPacksFields" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MasspaymentPacksFields() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MasspaymentPacksFields" /> class.
        /// </summary>
        /// <param name="PackId">PackId.</param>
        /// <param name="FromDate">Creation date of pack created with method create..</param>
        /// <param name="ToDate">Ending date of pack created with method create..</param>
        /// <param name="ApiPassword">ApiPassword (required).</param>
        public MasspaymentPacksFields(PackId PackId = default(PackId), string FromDate = default(string), string ToDate = default(string), ApiPassword ApiPassword = default(ApiPassword))
        {
            // to ensure "ApiPassword" is required (not null)
            if (ApiPassword == null)
            {
                throw new InvalidDataException("ApiPassword is a required property for MasspaymentPacksFields and cannot be null");
            }
            else
            {
                this.ApiPassword = ApiPassword;
            }
            this.PackId = PackId;
            this.FromDate = FromDate;
            this.ToDate = ToDate;
        }
        
        /// <summary>
        /// Gets or Sets PackId
        /// </summary>
        [DataMember(Name="pack_id", EmitDefaultValue=false)]
        public PackId PackId { get; set; }

        /// <summary>
        /// Creation date of pack created with method create.
        /// </summary>
        /// <value>Creation date of pack created with method create.</value>
        [DataMember(Name="from_date", EmitDefaultValue=false)]
        public string FromDate { get; set; }

        /// <summary>
        /// Ending date of pack created with method create.
        /// </summary>
        /// <value>Ending date of pack created with method create.</value>
        [DataMember(Name="to_date", EmitDefaultValue=false)]
        public string ToDate { get; set; }

        /// <summary>
        /// Gets or Sets ApiPassword
        /// </summary>
        [DataMember(Name="api_password", EmitDefaultValue=false)]
        public ApiPassword ApiPassword { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MasspaymentPacksFields {\n");
            sb.Append("  PackId: ").Append(PackId).Append("\n");
            sb.Append("  FromDate: ").Append(FromDate).Append("\n");
            sb.Append("  ToDate: ").Append(ToDate).Append("\n");
            sb.Append("  ApiPassword: ").Append(ApiPassword).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MasspaymentPacksFields);
        }

        /// <summary>
        /// Returns true if MasspaymentPacksFields instances are equal
        /// </summary>
        /// <param name="input">Instance of MasspaymentPacksFields to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MasspaymentPacksFields input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PackId == input.PackId ||
                    (this.PackId != null &&
                    this.PackId.Equals(input.PackId))
                ) && 
                (
                    this.FromDate == input.FromDate ||
                    (this.FromDate != null &&
                    this.FromDate.Equals(input.FromDate))
                ) && 
                (
                    this.ToDate == input.ToDate ||
                    (this.ToDate != null &&
                    this.ToDate.Equals(input.ToDate))
                ) && 
                (
                    this.ApiPassword == input.ApiPassword ||
                    (this.ApiPassword != null &&
                    this.ApiPassword.Equals(input.ApiPassword))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PackId != null)
                    hashCode = hashCode * 59 + this.PackId.GetHashCode();
                if (this.FromDate != null)
                    hashCode = hashCode * 59 + this.FromDate.GetHashCode();
                if (this.ToDate != null)
                    hashCode = hashCode * 59 + this.ToDate.GetHashCode();
                if (this.ApiPassword != null)
                    hashCode = hashCode * 59 + this.ApiPassword.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // FromDate (string) pattern
            Regex regexFromDate = new Regex(@"YYYY-MM-DD", RegexOptions.CultureInvariant);
            if (false == regexFromDate.Match(this.FromDate).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for FromDate, must match a pattern of " + regexFromDate, new [] { "FromDate" });
            }

            // ToDate (string) pattern
            Regex regexToDate = new Regex(@"YYYY-MM-DD", RegexOptions.CultureInvariant);
            if (false == regexToDate.Match(this.ToDate).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ToDate, must match a pattern of " + regexToDate, new [] { "ToDate" });
            }

            yield break;
        }
    }

}
