/* 
 * Tpay.com Technical Documentation
 *
 *  <p class=\"changes-disclaimer\"> Demo transaction/masspayments api key: <input type=\"text\" id=\"transaction_key\" value=\"75f86137a6635df826e3efe2e66f7c9a946fdde1\" class=\"ui-form-control\"/><label for=\"transaction_key\" style=\"display: none;\" id=\"tr_api_label\">COPIED!</label><br/><br/> Demo cards api key: <input type=\"text\" id=\"cards_key\" value=\"ba9a05faa697f9b43f39b84933ff168e373c6496\" class=\"ui-form-control\"/><label for=\"cards_key\" style=\"display: none;\" id=\"cards_api_label\">COPIED!</label><br/><br/> Demo registration api key: <input type=\"text\" id=\"registration_key\" value=\"6c0f5ef6e4d6877abad7fcfb3b5de117ad8b772d\" class=\"ui-form-control\"/><label for=\"registration_key\" style=\"display: none;\" id=\"registration_api_label\">COPIED!</label><br/><br/> The terms seller and merchant are used interchangeably and they both refer to a person or a company registered at tpay.com to accept online payments. <br/> Whenever term merchant panel is used it refers to the part of tpay.com website located at <a href=\"https://secure.tpay.com/panel\" target=\"_blank\">secure.tpay.com/panel</a>. <br/><br/> For sandbox purposes use merchant demo account <br/><br/> ID - 1010, Password - demo<br/><br/>Remember that this is a shared account, so all data passed through will be publicly visible.</p>
 *
 * OpenAPI spec version: 1.1.1
 * Contact: pt@tpay.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// error code (see transaction errors description table)
    /// </summary>
    /// <value>error code (see transaction errors description table)</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum TransactionErrorCodes
    {
        
        /// <summary>
        /// Enum ERR99 for value: ERR99
        /// </summary>
        [EnumMember(Value = "ERR99")]
        ERR99 = 1,
        
        /// <summary>
        /// Enum ERR98 for value: ERR98
        /// </summary>
        [EnumMember(Value = "ERR98")]
        ERR98 = 2,
        
        /// <summary>
        /// Enum ERR97 for value: ERR97
        /// </summary>
        [EnumMember(Value = "ERR97")]
        ERR97 = 3,
        
        /// <summary>
        /// Enum ERR96 for value: ERR96
        /// </summary>
        [EnumMember(Value = "ERR96")]
        ERR96 = 4,
        
        /// <summary>
        /// Enum ERR85 for value: ERR85
        /// </summary>
        [EnumMember(Value = "ERR85")]
        ERR85 = 5,
        
        /// <summary>
        /// Enum ERR84 for value: ERR84
        /// </summary>
        [EnumMember(Value = "ERR84")]
        ERR84 = 6,
        
        /// <summary>
        /// Enum ERR82 for value: ERR82
        /// </summary>
        [EnumMember(Value = "ERR82")]
        ERR82 = 7,
        
        /// <summary>
        /// Enum ERR63 for value: ERR63
        /// </summary>
        [EnumMember(Value = "ERR63")]
        ERR63 = 8,
        
        /// <summary>
        /// Enum ERR62 for value: ERR62
        /// </summary>
        [EnumMember(Value = "ERR62")]
        ERR62 = 9,
        
        /// <summary>
        /// Enum ERR61 for value: ERR61
        /// </summary>
        [EnumMember(Value = "ERR61")]
        ERR61 = 10,
        
        /// <summary>
        /// Enum ERR55 for value: ERR55
        /// </summary>
        [EnumMember(Value = "ERR55")]
        ERR55 = 11,
        
        /// <summary>
        /// Enum ERR54 for value: ERR54
        /// </summary>
        [EnumMember(Value = "ERR54")]
        ERR54 = 12,
        
        /// <summary>
        /// Enum ERR53 for value: ERR53
        /// </summary>
        [EnumMember(Value = "ERR53")]
        ERR53 = 13,
        
        /// <summary>
        /// Enum ERR52 for value: ERR52
        /// </summary>
        [EnumMember(Value = "ERR52")]
        ERR52 = 14,
        
        /// <summary>
        /// Enum ERR51 for value: ERR51
        /// </summary>
        [EnumMember(Value = "ERR51")]
        ERR51 = 15,
        
        /// <summary>
        /// Enum ERR45 for value: ERR45
        /// </summary>
        [EnumMember(Value = "ERR45")]
        ERR45 = 16,
        
        /// <summary>
        /// Enum ERR44 for value: ERR44
        /// </summary>
        [EnumMember(Value = "ERR44")]
        ERR44 = 17,
        
        /// <summary>
        /// Enum ERR43 for value: ERR43
        /// </summary>
        [EnumMember(Value = "ERR43")]
        ERR43 = 18,
        
        /// <summary>
        /// Enum ERR42 for value: ERR42
        /// </summary>
        [EnumMember(Value = "ERR42")]
        ERR42 = 19,
        
        /// <summary>
        /// Enum ERR41 for value: ERR41
        /// </summary>
        [EnumMember(Value = "ERR41")]
        ERR41 = 20,
        
        /// <summary>
        /// Enum ERR32 for value: ERR32
        /// </summary>
        [EnumMember(Value = "ERR32")]
        ERR32 = 21,
        
        /// <summary>
        /// Enum ERR31 for value: ERR31
        /// </summary>
        [EnumMember(Value = "ERR31")]
        ERR31 = 22
    }

}
